[package]
name = "villa_bot"
version = "0.1.0"
edition = "2021"
description = "provide simple access to villa open api"
authors = ["Golden_Water"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
